plugins:
  fontawesome_pro_icons_enabled:
    default: true
    client: true
  fa_icon_style:
    default: "regular"
    client: true
    type: enum
    choices:
      - regular
      - solid
      - light
      - thin
  fa_icon_family:
    default: "classic"
    client: true
    type: enum
    choices:
      - classic
      - sharp
      - sharp-duotone
      - duotone
